kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2beta1
metadata:
  name: flask-hpa
spec:
  scaleTargetRef:
    kind: Deployment
    name: flask
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Object
    object:
      target:
        kind: Service
        name: flask
      metricName: queue-length
      targetValue: 5000m